# Upload install files as an artifact.

# TODO: release and tag on v*.*.* commit message

name: CMake

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_PATH: ${{github.workspace}}/build
  BUILD_TYPE: Release
  INSTALL_PREFIX: ${{github.workspace}}/install
  PARALLEL_LEVEL: 2

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Configure
      run: cmake -B ${{env.BUILD_PATH}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{env.BUILD_PATH}} --config ${{env.BUILD_TYPE}} -j ${{env.PARALLEL_LEVEL}}

    - name: Test
      run: ctest --test-dir ${{env.BUILD_PATH}} -C ${{env.BUILD_TYPE}} -j ${{env.PARALLEL_LEVEL}}

    - name: Install
      run: cmake --install ${{env.BUILD_PATH}} --config ${{env.BUILD_TYPE}} --prefix ${{env.INSTALL_PREFIX}} --strip

    - name: Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{github.event.repository.name}}_${{github.ref_name}}_${{runner.os}}
        path: ${{env.INSTALL_PREFIX}}
